/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAttendanceRouteImport } from './routes/_shell.attendance'
import { Route as ShellCoursesRouteImport } from './routes/_shell.courses'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDepartmentsRouteImport } from './routes/_shell.departments'
import { Route as ShellMarksRouteImport } from './routes/_shell.marks'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellStudentsIndexRouteImport } from './routes/_shell.students.index'
import { Route as ShellStudentsStudentIdRouteImport } from './routes/_shell.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAttendanceRoute = ShellAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCoursesRoute = ShellCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDepartmentsRoute = ShellDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMarksRoute = ShellMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsIndexRoute = ShellStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudentsStudentIdRoute = ShellStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof ShellAttendanceRoute
  '/courses': typeof ShellCoursesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/departments': typeof ShellDepartmentsRoute
  '/marks': typeof ShellMarksRoute
  '/profile': typeof ShellProfileRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/students/': typeof ShellStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof ShellAttendanceRoute
  '/courses': typeof ShellCoursesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/departments': typeof ShellDepartmentsRoute
  '/marks': typeof ShellMarksRoute
  '/profile': typeof ShellProfileRoute
  '/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/students': typeof ShellStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/attendance': typeof ShellAttendanceRoute
  '/_shell/courses': typeof ShellCoursesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/departments': typeof ShellDepartmentsRoute
  '/_shell/marks': typeof ShellMarksRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/students/$studentId': typeof ShellStudentsStudentIdRoute
  '/_shell/students/': typeof ShellStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/marks'
    | '/profile'
    | '/students/$studentId'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/marks'
    | '/profile'
    | '/students/$studentId'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/attendance'
    | '/_shell/courses'
    | '/_shell/dashboard'
    | '/_shell/departments'
    | '/_shell/marks'
    | '/_shell/profile'
    | '/_shell/students/$studentId'
    | '/_shell/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/attendance': {
      id: '/_shell/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof ShellAttendanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/courses': {
      id: '/_shell/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ShellCoursesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/departments': {
      id: '/_shell/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof ShellDepartmentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/marks': {
      id: '/_shell/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof ShellMarksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/': {
      id: '/_shell/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof ShellStudentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/students/$studentId': {
      id: '/_shell/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof ShellStudentsStudentIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAttendanceRoute: typeof ShellAttendanceRoute
  ShellCoursesRoute: typeof ShellCoursesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDepartmentsRoute: typeof ShellDepartmentsRoute
  ShellMarksRoute: typeof ShellMarksRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellStudentsStudentIdRoute: typeof ShellStudentsStudentIdRoute
  ShellStudentsIndexRoute: typeof ShellStudentsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAttendanceRoute: ShellAttendanceRoute,
  ShellCoursesRoute: ShellCoursesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDepartmentsRoute: ShellDepartmentsRoute,
  ShellMarksRoute: ShellMarksRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellStudentsStudentIdRoute: ShellStudentsStudentIdRoute,
  ShellStudentsIndexRoute: ShellStudentsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
